/*
 * Copyright (C) 2016 Pajato Technologies LLC.
 *
 * This file is part of Pajato GameChat.

 * GameChat is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.

 * GameChat is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.

 * You should have received a copy of the GNU General Public License along with GameChat.  If not,
 * see http://www.gnu.org/licenses
 */

package com.pajato.android.gamechat.chat;

import android.content.Context;
import android.content.Intent;
import android.support.annotation.NonNull;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.View;

import com.pajato.android.gamechat.R;
import com.pajato.android.gamechat.account.Account;
import com.pajato.android.gamechat.account.AccountManager;
import com.pajato.android.gamechat.chat.model.Group;
import com.pajato.android.gamechat.common.Dispatcher;
import com.pajato.android.gamechat.common.FabManager;
import com.pajato.android.gamechat.common.InvitationManager;
import com.pajato.android.gamechat.common.adapter.MenuEntry;
import com.pajato.android.gamechat.event.AccountStateChangeEvent;
import com.pajato.android.gamechat.event.ClickEvent;
import com.pajato.android.gamechat.event.JoinedRoomListChangeEvent;
import com.pajato.android.gamechat.event.ProfileGroupChangeEvent;
import com.pajato.android.gamechat.event.TagClickEvent;

import org.greenrobot.eventbus.Subscribe;

import java.util.ArrayList;
import java.util.List;

import static com.pajato.android.gamechat.chat.ChatFragmentType.showNoJoinedRooms;

/**
 * Provide a fragment class that decides which alternative chat fragment to show to the User.
 *
 * @author Paul Michael Reilly (based on GameFragment written by Bryan Scott)
 */
public class ChatFragment extends BaseChatFragment {

    // Public constants.

    /** The lookup key for the FAB game home memu. */
    public static final String CHAT_HOME_FAM_KEY = "chatHomeFamKey";

    // Public instance methods.

    /** Set the layout file, which specifies the chat FAB and the basic options menu. */
    @Override public int getLayout() {return R.layout.fragment_chat;}

    /** Handle a authentication change event by dealing with the fragment to display. */
    @Subscribe public void onAccountStateChange(final AccountStateChangeEvent event) {
        // Simply start the next logical fragment.
        ChatManager.instance.startNextFragment(this.getActivity());
    }

    /** Process a given button click event looking for the chat FAB. */
    @Subscribe public void onClick(final ClickEvent event) {
        // Determine if this event is for the chat fab button.
        View view = event.view;
        logEvent(String.format("onClick: with event {%s};", view));
        switch (view.getId()) {
            case R.id.chatFab:
                // It is a chat fab button.  Toggle the state.
                FabManager.chat.toggle(this);
                break;
            default:
                // Determine if the button click was generated by a group view or room view drill
                // down.  Handle it by adding the next fragment to the back stack.
                processPayload(event.view);
                break;
        }
    }

    /** Process a menu click event ... */
    @Subscribe public void onClick(final TagClickEvent event) {
        Object payload = event.view.getTag();
        if (payload == null || !(payload instanceof MenuEntry)) return;

        // The event represents a menu entry.  Close the FAM and case on the title id.
        FabManager.chat.dismissMenu(this);
        MenuEntry entry = (MenuEntry) payload;
        switch (entry.titleResId) {
            case R.string.AddGroupMenuTitle:
                // Dismiss the FAB menu, and start up the add group activity.
                Intent intent = new Intent(this.getActivity(), AddGroupActivity.class);
                startActivity(intent);
                break;
            case R.string.JoinRoomMenuTitle:
                showFutureFeatureMessage(R.string.JoinRoomDesc);
                break;
            case R.string.AddRoomMenuTitle:
                showFutureFeatureMessage(R.string.AddRoomDesc);
                break;
            default:
                // ...
                break;
        }
    }

    /** Post the chat options menu on demand. */
    @Override public void onCreateOptionsMenu(final Menu menu, final MenuInflater menuInflater) {
        menuInflater.inflate(R.menu.chat_menu_base, menu);
    }

    /** A new group loaded event has been detected.  Join it if not already joined. */
    @Subscribe public void onGroupProfileChange(final ProfileGroupChangeEvent event) {
        // Ensure that the User is logged in (a prompting will be generated if not.)
        Account account = AccountManager.instance.getCurrentAccount(getContext());
        if (account == null) return;

        // Ensure that a group key and group are packaged in the event.
        String groupKey = event.key;
        Group group = event.group;
        if (groupKey != null && group != null)
            // The group and key are available.  Accept any open invitations.
            InvitationManager.instance.acceptGroupInvite(account, group, groupKey);
    }

    /** Create the view to do essentially nothing. Things will happen in the onStart() method. */
    @Override public void onInitialize() {
        // Declare the use of the options menu and intialize the FAB and it's menu.
        super.onInitialize();
        FabManager.chat.setTag(this.getTag());
        FabManager.chat.setMenu(CHAT_HOME_FAM_KEY, getHomeMenu());
    }

    /** Deal with a change in the joined rooms state. */
    @Subscribe public void onJoinedRoomListChange(@NonNull final JoinedRoomListChangeEvent event) {
        // Turn off the loading progress dialog and handle a signed in account with some joined
        // rooms by rendering the list.
        if (event.joinedRoomList.size() == 0) {
            // Handle the case where there are no joined rooms by enabling the no rooms message.
            ChatManager.instance.replaceFragment(showNoJoinedRooms, this.getActivity());
        }
    }

    /** Dispatch to a more suitable fragment. */
    @Override public void onResume() {
        // The experience manager will load a fragment to view into this envelope fragment.
        super.onResume();
        ChatManager.instance.startNextFragment(getActivity());
    }

    /** Setup the fragment with what would otherwise be constructor arguments. */
    @Override public void onSetup(final Context context, final Dispatcher dispatcher) {

    }

    // Private instance methods.

    /** Return the home FAM used in the top level show games and show no games fragments. */
    private List<MenuEntry> getHomeMenu() {
        final List<MenuEntry> menu = new ArrayList<>();
        menu.add(getTintEntry(R.string.JoinRoomMenuTitle, R.drawable.vd_casino_black_24px));
        menu.add(getTintEntry(R.string.AddRoomMenuTitle, R.drawable.vd_casino_black_24px));
        menu.add(getTintEntry(R.string.AddGroupMenuTitle, R.drawable.ic_group_add_black_24dp));
        return menu;
    }
}
